name: main
on: [push, pull_request, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm ls
      - run: ./node_modules/.bin/eslint ./
      - run: ./node_modules/.bin/stylelint ./**/*.css ./**/*.html ./**/*.js

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - uses: actions/cache@v4
        with:
          path: |
            _site-root/
            _site/
          key: generated-site-dir
      - uses: actions/jekyll-build-pages@v1
      - run: |
          mkdir -p _site-root
          ln -s ../_site/ _site-root/${{ github.event.repository.name }}

  local-links-check:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/cache@v4
        with:
          path: |
            _site-root/
            _site/
          key: generated-site-dir
      - uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
          pages_path: ./_site-root/
          cmd_params: >
            --buffer-size=8192 --color=always --skip-tls-verification
            --include="^https://${{ github.repository_owner }}[.]github[.]io/${{ github.event.repository.name }}/"
            --exclude="^https://github[.]com/rspamd/rspamd[.]com/edit/master/"
            --exclude="^https://${{ github.repository_owner }}[.]github[.]io/${{ github.event.repository.name }}/(doc/lua/((lua|rspamd)_.+|ucl)[.]html(#.+)?|.*#top)$"

  external-links-check:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/cache@v4
        with:
          path: |
            _site-root/
            _site/
          key: generated-site-dir
      - uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
          pages_path: ./_site-root/
          cmd_params: >
            --buffer-size=8192 --color=always --skip-tls-verification
            --verbose --max-connections=10
            --exclude="^https://${{ github.repository_owner }}[.]github[.]io/${{ github.event.repository.name }}/"
            --exclude="^https://github[.]com/rspamd/rspamd[.]com/edit/master/"
            --exclude="^https://rspamd[.]com/${{ github.event.repository.name }}/$"
            --exclude="^https://www[.]ozon[.]ru/$"
            --exclude="^https://rspamd[.]com/${{ github.event.repository.name }}/."
